apiVersion: v1
kind: Pod
metadata:
  name: elasticsearch
  labels:
    app: log-store
spec:
  containers:
  - name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    ports:
      - containerPort: 9200
        name: log-agent-port
      - containerPort: 9300
        name: kibana-port

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
spec:
  selector:
    app: log-store
  ports:
  - name: log-agent-port
    protocol: TCP
    port: 9200
    targetPort: 9200
  - name: kibana-port
    protocol: TCP
    port: 9300
    targetPort: 9300

