apiVersion: v1

kind: ConfigMap

metadata:

  name: fluentd-config

data:

  fluent.conf: |

    <source>

      @type tail

      format none

      path /var/log/1.log

      pos_file /var/log/1.log.pos

      tag count.format1

    </source>

    <source>

      @type tail

      format none

      path /var/log/2.log

      pos_file /var/log/2.log.pos

      tag count.format2

    </source>


    <match **>
      @type elasticsearch
      host elasticsearch-service
      port 9200
      user elastic
      password  scYJk-UnlqKsQMsTBhmj 
      ssl_verify false
      ssl_version TLSv1_2
      ca_file /etc/ssl/certs/secret_ca.crt
      scheme https
      index_name fluentd
      type_name fluentd
    </match>    

