apiVersion: v1
kind: Pod
metadata:
  name: kibana
  labels:
    app: log-ui
spec:
  containers:
  - name: kibana
    image: docker.elastic.co/kibana/kibana:8.6.0
    ports:
      - containerPort: 5601
        name: http-web-svc

---
apiVersion: v1
kind: Service
metadata:
  name: kibana-service
spec:
  selector:
    app: log-ui
  type: LoadBalancer
  ports:
  - name: kibana-service-port
    port: 8080
    targetPort: 5601
